#!/bin/bash
    
    # Directory build for quick games
    # Author: Shawn Scott

# TODO: have the git repo created on Github upon this script getting called
# TODO: Update game template to use
cd ~/Desktop
git clone "$1" && cd "$(basename "$1" .git)"
npm install
code .