#!/bin/bash

# Simple note-taking script
# Alias => note
# Author: Shawn Scott

# Help message
if [[ $1 = "-h" ]] || [[ $1 = "--help" ]]
then
  echo "
$(basename "$0") [-h] (name)
  -- script to track notes

where:
  -h (--help) show help text
"
  exit 0;
fi

# Store the date using standard `date` format
printf -v date "%(%a %e %b %X %Z %Y)T\n" -1
date=$(date)

# Store topic if given
if [ -z "$1" ]
  then
    topic="notes"
  else
    topic="$1"
fi

# Filename to write to
filename="$topic.txt"

# Path to send file
path="$HOME/Desktop/scripts/notes/$filename"

# Ask the user for input, reference => help read
read -e -p "Add note: " note

# Note template
echo "_______________________________________________________
Author: $USER ($UID)
Date: $date
Host: ${HOSTNAME:-`hostname`}

Note: $note
" >> "$path"    # Good practice to wrap variables with double quotes

# Message to user
echo "Note '$note' saved to: $path"