#!/bin/bash
    
# Builds Bash Scripting files
# Author: Shawn Scott

if [ -z "$1" ]
  then
    echo "Please give a name for your script file";      
  else
    touch $1;
    chmod u+x $1;
    echo "#!/bin/bash
    
# $1
# Author: Shawn Scott
" >> $1;
    
    mv $1 ~/Desktop/scripts/$1;
fi