#!/bin/bash

# Simple note-taking script
# Alias => note
# Author: Shawn Scott

# Store the date using standard `date` format
printf -v date "%(%a %e %b %X %Z %Y)T\n" -1

# Store topic if given
if [ -z "$1" ]
  then
    topic="notes"
  else
    topic="$1"
fi

# Filename to write to
filename="$topic.txt"

# Path to send file
path="$HOME/Desktop/scripts/notes/$filename"

# Ask the user for input, reference => help read
read -e -p "Add note: " note

# Note template
echo "_______________________________________________________
Author: $USER ($UID)
Date: $date
Host: ${HOSTNAME:-`hostname`}

Note: $note
" >> "$path"    # Good practice to wrap variables with double quotes

# Message to user
echo "Note '$note' saved to: $path"
