#!/bin/bash

# signature

# Help message
if [[ $1 = -h ]] || [[ $1 = --help ]]
then
  echo "
$(basename "$0") [-h] (name)
  -- script to echo the signature to the console

where:
  -h (--help) show help text

  exit 0;"
fi

printf "\e[31m
 _______                            _______              
|   _   |_                         |   _   |           
|   |___| |                        |   |___|          _________
'____   | '---.-----.--.--.--.-.--.'____   .-----.---|__  _  __|
|   |   | .-. |  -  |  |  |  | .-. |   |   |  |--|  -  |  |  |
|       '_| |_'___'_'___/\___'_| |_'       '_____'_____'__|__'
'-------'                          '-------'        \e[36m@BadassBison\e[00m
\n"

